sudo: required

language: generic

matrix:
  include:
    - os: linux
      env: COMPILER=4.02.3
    - os: linux
      env: COMPILER=4.03.0
    - os: linux
      env: COMPILER=4.04.2
    - os: linux
      env: COMPILER=4.05.0
    - os: linux
      env: COMPILER=4.06.1
    - os: linux
      env: COMPILER=4.07.1
    - os: linux
      env: COMPILER=4.08.1
    - os: linux
      env: COMPILER=4.09.0
    - os: osx
      env: COMPILER=4.09.0

script: bash -e src/travis.sh

cache:
  directories:
    - $HOME/.opam
    - ./_opam

notifications:
  email:
    on_success: always
    on_failure: always
