sudo: required

language: generic

matrix:
  include:
    - os: osx
      env: COMPILER=4.10.0
    - os: linux
      env: COMPILER=4.10.0
    - os: linux
      env: COMPILER=4.09.0
    - os: linux
      env: COMPILER=4.08.1
    - os: linux
      env: COMPILER=4.07.1
    - os: linux
      env: COMPILER=4.06.1
    - os: linux
      env: COMPILER=4.05.0
    - os: linux
      env: COMPILER=4.04.2
    - os: linux
      env: COMPILER=4.03.0
    - os: linux
      env: COMPILER=4.02.3

before_install:
  - '[ "$TRAVIS_EVENT_TYPE" != cron ] || rm -rf ~/.opam ./_opam'

install:
  - |
    case $TRAVIS_OS_NAME in
      linux)
        sudo apt-get update -qq
        sudo apt-get install -qq libev-dev
        OS=linux
        ;;
      osx)
        brew update > /dev/null
        brew install libev gtk+
        OS=macos
        ;;
    esac

  - VERSION=2.0.5
  - FILENAME=opam-$VERSION-x86_64-$OS
  - wget https://github.com/ocaml/opam/releases/download/$VERSION/$FILENAME
  - sudo mv $FILENAME /usr/local/bin/opam
  - sudo chmod a+x /usr/local/bin/opam

  - opam init -y --bare --disable-sandboxing --disable-shell-hook
  - |
    if [ ! -d _opam/bin ]
    then
      rm -rf _opam
      opam switch create . $COMPILER $REPOSITORIES --no-install
    fi
  - eval `opam config env`
  - opam --version
  - ocaml -version

  - opam install conf-libev
  - opam pin add -y --no-action lwt_glib .
  - opam install -y --deps-only lwt_glib

script:
  - opam install -y --verbose lwt_glib
  - opam lint
  - |
    if [ "$COMPILER" != "4.02.3" ]
    then
      opam install -y 0install
    fi

before_cache:
  - opam remove -y 0install lwt_glib
  - opam pin remove -y lwt_glib
  - opam clean

cache:
  directories:
    - $HOME/.opam
    - ./_opam

notifications:
  email:
    on_success: always
    on_failure: always
